export default {
  //LIVE
  BASE_URl: "https://example.com/", // placeholder for sample code

  //LOCAL
  //  BASE_URl: "http://192.168.1.100/lbs/",

  PUBLISH_KEY: "pk_test_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",

  VEIFY_IDENTITY_TEMPLATE_ID: "itmpl_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",

  NEW_SIGNUP_REQUEST: "NEW_SIGNUP_REQUEST",
  NEW_SIGNUP_SUCCESS: "NEW_SIGNUP_SUCCESS",
  NEW_SIGNUP_FAILURE: "NEW_SIGNUP_FAILURE",

  SIGNIN_REQUEST: "SIGNIN_REQUEST",
  SIGNIN_SUCCESS: "SIGNIN_SUCCESS",
  SIGNIN_FAILURE: "SIGNIN_FAILURE",

  FORGOT_PASSWORD_REQUEST: "FORGOT_PASSWORD_REQUEST",
  FORGOT_PASSWORD_SUCCESS: "FORGOT_PASSWORD_SUCCESS",
  FORGOT_PASSWORD_FAILURE: "FORGOT_PASSWORD_FAILURE",

  CHANGE_PASSWORD_REQUEST: "CHANGE_PASSWORD_REQUEST",
  CHANGE_PASSWORD_SUCCESS: "CHANGE_PASSWORD_SUCCESS",
  CHANGE_PASSWORD_FAILURE: "CHANGE_PASSWORD_FAILURE",

  EDIT_PROFILE_REQUEST: "EDIT_PROFILE_REQUEST",
  EDIT_PROFILE_SUCCESS: "EDIT_PROFILE_SUCCESS",
  EDIT_PROFILE_FAILURE: "EDIT_PROFILE_FAILURE",

  USER_DETAILS_REQUEST: "USER_DETAILS_REQUEST",
  USER_DETAILS_SUCCESS: "USER_DETAILS_SUCCESS",
  USER_DETAILS_FAILURE: "USER_DETAILS_FAILURE",

  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",

  TERMS_OF_SERVICE_REQUEST: "TERMS_OF_SERVICE_REQUEST",
  TERMS_OF_SERVICE_SUCCESS: "TERMS_OF_SERVICE_SUCCESS",
  TERMS_OF_SERVICE_FAILURE: "TERMS_OF_SERVICE_FAILURE",

  PRIVACY_POLICY_REQUEST: "PRIVACY_POLICY_REQUEST",
  PRIVACY_POLICY_SUCCESS: "PRIVACY_POLICY_SUCCESS",
  PRIVACY_POLICY_FAILURE: "PRIVACY_POLICY_FAILURE",

  ABOUT_US_REQUEST: "ABOUT_US_REQUEST",
  ABOUT_US_SUCCESS: "ABOUT_US_SUCCESS",
  ABOUT_US_FAILURE: "ABOUT_US_FAILURE",

  CATEGORY_LISTING_REQUEST: "CATEGORY_LISTING_REQUEST",
  CATEGORY_LISTING_SUCCESS: "CATEGORY_LISTING_SUCCESS",
  CATEGORY_LISTING_FAILURE: "CATEGORY_LISTING_FAILURE",

  SOUNDTRACK_LISTING_REQUEST: "SOUNDTRACK_LISTING_REQUEST",
  SOUNDTRACK_LISTING_SUCCESS: "SOUNDTRACK_LISTING_SUCCESS",
  SOUNDTRACK_LISTING_FAILURE: "SOUNDTRACK_LISTING_FAILURE",

  SOUNDTRACK_VIEW_REQUEST: "SOUNDTRACK_VIEW_REQUEST",
  SOUNDTRACK_VIEW_SUCCESS: "SOUNDTRACK_VIEW_SUCCESS",
  SOUNDTRACK_VIEW_FAILURE: "SOUNDTRACK_VIEW_FAILURE",

  SOUNDTRACK_DETAILS_REQUEST: "SOUNDTRACK_DETAILS_REQUEST",
  SOUNDTRACK_DETAILS_SUCCESS: "SOUNDTRACK_DETAILS_SUCCESS",
  SOUNDTRACK_DETAILS_FAILURE: "SOUNDTRACK_DETAILS_FAILURE",

  UPDATE_FAVORITE_STATUS: "UPDATE_FAVORITE_STATUS",

  ADD_TO_FAVORITES_REQUEST: "ADD_TO_FAVORITES_REQUEST",
  ADD_TO_FAVORITES_SUCCESS: "ADD_TO_FAVORITES_SUCCESS",
  ADD_TO_FAVORITES_FAILURE: "ADD_TO_FAVORITES_FAILURE",

  FAVORITES_LIST_REQUEST: "FAVORITES_LIST_REQUEST",
  FAVORITES_LIST_SUCCESS: "FAVORITES_LIST_SUCCESS",
  FAVORITES_LIST_FAILURE: "FAVORITES_LIST_FAILURE",

  QUIZ_QUESTION_LIST_REQUEST: "QUIZ_QUESTION_LIST_REQUEST",
  QUIZ_QUESTION_LIST_SUCCESS: "QUIZ_QUESTION_LIST_SUCCESS",
  QUIZ_QUESTION_LIST_FAILURE: "QUIZ_QUESTION_LIST_FAILURE",

  QUIZ_RESULT_REQUEST: "QUIZ_RESULT_REQUEST",
  QUIZ_RESULT_SUCCESS: "QUIZ_RESULT_SUCCESS",
  QUIZ_RESULT_FAILURE: "QUIZ_RESULT_FAILURE",

  MY_QUIZ_LIST_REQUEST: "MY_QUIZ_LIST_REQUEST",
  MY_QUIZ_LIST_SUCCESS: "MY_QUIZ_LIST_SUCCESS",
  MY_QUIZ_LIST_FAILURE: "MY_QUIZ_LIST_FAILURE",

  IS_FROM_ROOT: "IS_FROM_ROOT",

  DEFAULT_API_FAILURE: "DEFAULT_API_FAILURE",
};
